a = ''.join('''YFRTIPWCQYKADHIPRAKYPNPWGVFPYVYFIIEVGQEVHLANFHTSYMLLHPDCYYDI
LGFACATVTLRMAKWMYFICKYCDHRRPYWMNFVELPGQQNPCMTQHAQWWSPYHTCWYT
KTRCPEGGDRKRWSGWTCFHWHAYLWIHAHWCLRPQLVYTIYFSANRVTWTETKPPDINS
KKQPLGTDLRAECATRDSPPKEHVPGHKMFSPYTWTDYPIIHTACWKWHNFTITFHLGEC
SYTTQGTNTHDLMWSKHKILDDHRGDDGVCCMYAPCWQLFYLDVNKWWEFKMIDEAGTFQ
WTNADCNFPQGFVRDLSVNMDGHHDTKYMADCEGNWLQWMEKRMAQGAWWTLPQCKRFCD
CGSKMSHGEAMIHDMHGKKHVNNHLMPWGHFDIPWITTLWVPQRHNIFDRAKDYFRWMKG
WYIIRDTKAIVTVAFGDAGFCYWEYLHIIWGPNLCPKQAYSNHLSQGTEYTWHTVQMGHF
FMVWHVRHIDVFFGRLMSDLKMTNECGGPYHTCDNIWQFWCTPNSMARHISFPYFSGWVM
GVMRFPLSMHQQRNHPQTTEFWMDSPRQHNEWTYDKMIMSPMWGAEWPATGSGYMVYQTD
FAHFPALMAPSHEWKIGRSNSKHKYGMAMLQYTGNFAYCGYEKTQWISRHNCIRCGNYRS
VFKGARFKVVQIDYYNCFGLTSTFLWGWHWVEFFDHTPSPKVSECLREFYETDQHQCWMP
MYSPMLDCVQEQFRHNSEIVSLVWCSVCYTF'''.split())

b = ''.join('''YFRTIKWCQYKIATSNSVDQHIFGAKYPNPQKLQNFGVTGYVYFIIFVGQEVHLLLHPEV
QQCYYDIHGFACATVTLRMNKWMREKHHIFYNCGEICIWNHQYEDYDPYWMNFVEYMSFD
EIAMPGQGNWCMTQHAQWWSPYVCTQHSPENSIIGCTHGMEDTAGWKCFEWWCCYDWPQL
MCYCYQCINCAYNSRIYFSANRVTWTENPDLNSKKQPLGTDLRAECATRSSEPCEYGHKL
EACHIFPPYQWTDYPIKHTACWIESRGQSWTNCTITFHLGENNLSGYTTQGTNTHDIKSK
IFDRMWMIEKILDDCRTDDGVCYMIVLSYMYWQLFYLDVNKWWPSWQRCFNPPQGFVRDH
PVNMDGHHDWGEKECHIMSTNWLQWMAWWTLCQKMSHGWHHPAFKVTMIHPEHLQKSGAW
GHYDIIWITLLDELWVPQQHETNSASAWTIACSDRAKDWIIRDTFRAIVHQEVASPVNFM
WDQQPQSDHQNKEQAGFCYWEYLHIIWGPVLGFWLLSTKAKMMKCCVSAYSNHLSQGTDY
YWHTVQFQSHVGGHFFHVRHIDVFFGRLDSDLKMDNECGGGPAQQFWCTPNCMARHIDMP
VMRFTLSMHQQRNYPQTTIFWMDSPRQDNRWCYRMGSYRKMLMSPMWGATDNLEWFRAYP
MTGNQYMVYQTEFAHFPALMVPSHEWKEYCHICHFQHKGLWNTSPYMKTQWRSRHNCIRC
GNYRKVFKGARFKFGLTSFAPKCVLQRMWVEFCYKHFNMNHEPYETDQWQCDSTIMPNYS
PMGGDPWDCVQEQFRHNSEIVSYVWCSVCYTF'''.split())

def distance(a, b):
    t=[[]]
    for n in range(len(b)+1):
        t[0].append(n)
    for i in range(1, len(a)+1):
        t.append([i] + [0]*len(b))
        for j in range(1, len(b)+1):
            if a[i-1] == b[j-1]:
                t[i][j] = t[i-1][j-1]
            else:
                t[i][j] = min(t[i-1][j], t[i][j-1], t[i-1][j-1]) + 1
    return t[len(a)][len(b)]

print(distance(a, b))
