import itertools

text = 'TATGACCGGTTGCCTGAACGCTCAGAATCTATATAGCTCCTTGATAGTTGTATTATATGCACAGTGGATTCAATGGCTTCACCATTCAGCAGTCGTTGTCATATATTGCAGCCCGCCCAAATCGTGATATCCCCATGTCTGCCGCTGAGACCTAGGGCGAGCCTCGAACAGGTCCTCATGGTGGCTTGGACTGATCATAAACGAAAGTATGACCAGTCCACGTCTCACTTGAAACGATAGTGTCAGTTACCGCCGATTCGTTTTGTCAGGTGTCGATCGTAGGACCAAGTGATATCATTATCCTGGTAGGGCACTCATGCTCTTACCGAATTAACCCGTTCGTCTTTTTTGATGGCACGGTGTGCGAGAGAAACTTCCCTAGGGGACACGTCTCATTTAAACGGCACAGAGGACTCAAAAGTTCCAATAGACATTGGCTTCTTAATTTGGACGTAAGCCGGCGCGGTTACTTTCTATAGAACTGCAGGAGGAGCAGCGTAGACACTATCCTCGGTCGCCGAGTTTTTTCCACGCTGGGGATGAGACGACCACTGTAGTATGGGCAGCCCAGTTCAGGCTCACAGTCCATAGGCCTTAGGTGCCTTGCCAGAAACCTCATTCACCGGAGACTCGCGAGGTATGTCCCAACAACCAATGACTTTTTGTAGGCGCATAGCCCGATGTACAGAGAGACCCCAACGCCTCGGGACCACGCAACGTGTGACTAGTCCGATCTGGTTACCT'
k = 8

bases = ['A', 'C', 'G', 'T']
kmers = [''.join(p) for p in itertools.product(bases, repeat=k)]

out=[]
for kmer in kmers:
    c=0
    for i in range(len(text)-k+1):
        if text[i:i+k] == kmer:
            c+=1
    out.append(str(c))
print(' '.join(out))
