string = 'CGTTACTGATCGTGAACTGACCGAACCACCGAACCCTTGGAACGCGTTACTGAACCGAACCTCGTGAACTGACCGAACCACCGAACCTAAATGCCTAAATGCCTAAATGCCCTTGGAACGCTTGGAACGCTTGGAACGCGTTACTGACGTTACTGACTTGGAACGCGTTACTGATAAATGCCTAAATGCCTCGTGAACTGACCGAACCCTTGGAACGTAAATGCCTAAATGCCTAAATGCCACCGAACCTAAATGCCCTTGGAACGTAAATGCCCTTGGAACGCGTTACTGATAAATGCCACCGAACCCGTTACTGATCGTGAACTGCGTTACTGAACCGAACCCTTGGAACGTCGTGAACTGACCGAACCACCGAACCTCGTGAACTGCTTGGAACGTCGTGAACTGCTTGGAACGTAAATGCCCGTTACTGACTTGGAACGTAAATGCCCGTTACTGACTTGGAACGTAAATGCCTAAATGCCCTTGGAACGTCGTGAACTGCGTTACTGACTTGGAACGTCGTGAACTGCTTGGAACGTCGTGAACTGTAAATGCCTAAATGCCCGTTACTGATAAATGCCTAAATGCCACCGAACCTAAATGCCTCGTGAACTGCTTGGAACGTCGTGAACTGACCGAACCCTTGGAACGCTTGGAACGTCGTGAACTGCTTGGAACGACCGAACCCTTGGAACGTAAATGCCTCGTGAACTGCGTTACTGATAAATGCCCTTGGAACGCGTTACTGATCGTGAACTGCGTTACTGACTTGGAACGACCGAACCTCGTGAACTGTAAATGCCTAAATGCCTCGTGAACTGTAAATGCCCTTGGAACGCGTTACTGAACCGAACCCGTTACTGACTTGGAACGACCGAACCTCGTGAACTGTCGTGAACTGCGTTACTGAACCGAACCCTTGGAACGCTTGGAACGTCGTGAACTG'
k = 11

c={}
for i in range(len(string)-k+1):
    kmer = string[i:i+k]
    if kmer in c:
        c[kmer] += 1
    else:
        c[kmer] = 1

out=[]
for k, v in c.items():
    if v == max(c.values()):
        out.append(k)
print(' '.join(out))
