codon={}
with open("codon.txt") as f1:
    for line in f1:
        n = line.strip().split()
        codon[n[0]] = n[1]
        codon[n[2]] = n[3]
        codon[n[4]] = n[5]
        codon[n[6]] = n[7]

count={}
for aa in codon.values():
    if aa in count:
        count[aa] += 1
    else:
        count[aa] = 1

n=1        
protein = 'MSWMFKTAIHFQRSPRKTVMHISKYDVVVSLEAVRRKAHPYDPTQDHLLQQTEKGEHGVVGTFDSPYFSFCPNYTHCRPITRNPPYNLICMMDYFTIEAVWHNSEKDPGTEGTCRNLPSCNIWCGAVWYDPLSRNPISPENQYIHIAVYGFFTKMPAWWCMKVWMPQHDVVAHTCTRVLAMFYYQWQMMHLECIFEVLYWKGKLDGCWTTKQNPYICIHCWINHHYVASMYVQMWVEHVEDKVAKNKSSPIRTEAMYQGTQFYHWTFAGMQACRAVDIHEEFRERQCWTDKWMGWGTPEQMTPWAIGWGDSKIHRSFATIYQACTPVMHIMWWSLTGTGEMSNYKCSYIYKTENEQQFAMFFWHERFHENQYMVCYLEALWMQKPHGERQGLATSYGALETLAMHYHNWDQIHVILLSNFWRGYFWPTEVFQRKYFEQMGYHVRERKGIWHSLRTMAKKPMIMPTSAYCRQVRMRVKDEIALMQDVWTFDLWDAHPRVCFLERLGWHGDWHMTAAIDLMGVPSAHWDHFCCNPHCALQGVPAGKRTCIVAMDFPAENYFTYHDDRSKTYVTDCMVGAVRTYPHLRITEAHKFTKKFVNIVACIICLDSMILGHPAQTRWMFLEWHIYDIDFEPDVIVRMKWFEHTSKRMSVFRDHVMMTSYLSREADKFYSHGEVPTHMAPNNSIAAAVGWARWYPRECLHAGRNEPAFHLPVFHAVDSIQQLWCMSWCVRGQYFIIYEHCNADDIENWENIYLDTDGFGDKGFTKQKCHLYYSYPMCLVETTQVKHFYKFWFVDCWHHGMARFNMVHVPTCIRVCKAARRMREMMGLFSESVYQSSPYMEGRIAPTTKHAVFRIHEAPFNSCKYDNTYERTRAAGTTKYFREDKRMGRGHTSEQEFCIPHPNLTEPWSWVLYDPYYPCMKFQRCHYELWHEKANVHGRISCGHICWDTGGTEENFSPLMWRGQDAAGREATLREAKKMNFVLCESYECCHNITMLY'
for a in protein:
    n *= count[a]

print(str(n*3)[-6:])
