a = ''.join('''TCAATCGGCATACACGCCTTGGAGTACAGCGCAAAAAGGCTCGGTAACTTGCCGTACGGC
TCCCGGACCTTCCAGTGTCAATTGTACAACTCAGTTGGAGCATTTTCAGTAGACGCAAAT
GACAATGTTCGACGGGCTTTCCCGGTTGCTCGGCCGGGCGCCATAGTTTCACTGAGAAAA
GCTAGTGCGCTATCTTAAACCCCACCAACTGCTAATACAAGGGATCGTAGGCGCAGAGAG
CACCGAGGTTTCAAGATACGAATCGCGTAGGTACCGAAAGCGTGCGGAAAAATGATTACC
CAGGCACGCGACGCATTGTTGGCCGACCAAAACTGGCTACCCTACGGGAGTTGGGACTTG
GCTTCACGGTCCGTTGGCGCATTAAAAAATGGTCACTCGGTCACCAGGCGGGTAGCACTT
CGGGCTCCCGGTTCATCTATGAATCAGAGGAAGGCTCTCGATATCCTATGGACCCCTCGT
AGTAAGATCCGCCCATCGCTCTATAGGGTGGTCCAAATCGTCGTTCGTTTGCGGTAGCTA
ACGTGGACTGCGAACAACCTTTGTTGGTAGATCAGGCCAATGAACGACTTGGCGTGTACC
ACACAGACCTTTTGGGCGCAATATGGGCCCTAGTAAATGTCTGCTATTTATACCAAAACC
AGGCAAGCGAATTGAGCCTTCCCCCCTGGAAGTTTCATGAAAACTTACTTATAGCCCGCT
CCTTGTAAGCTAGGTCTTATTACAGATATTGGATTACGCCGTTACCAGCTTGTCATGGTC
GAAGCTGACTTATCGGGTGCCTCTGTCTCCCCTTTCTAGAGTCTTGATCTCTTTATC'''.split())

b = ''.join('''GAGGTACGCCGCAGGGTCCCAGGTTGCCGGGCGAAGGTGGCGTGGATTATTATAAAGCCG
AGGACAACAAGTCTAAGCACGTAGCGTCAGAACTGAAACAACTTAACACACGCGCGCATC
TGGAGGCCGGAAGTCGGTGACTTGCAGCTAGAGACATTTCCGTATTTCCACGCATGATCC
TAGGGATCGGATAGTGACCACCCAGGGTAGACAGTGTGAGCTCAAGATTCGAGTGACTGA
TGGAATAAATATCGGGGTGGACATTACCGAGGGATAGGCGTTACGATATCACGATCTAAG
CGATTCTGGTCCAAATTGTGGACCCGCGCAGTCGCGCTGGGCGCACGGTCGTTACATCGG
GTCTCGTTAAGGAGCGTCATAATATCTGAGGAGTATTCACCGAAGCCAGCTTAATCTGCC
TGTGCTAATCCATGACATGTGGAGCAGTCCCTGGTGAGAGAGCTAAATACTATGCGCCGC
GTATAGGGATGAACAGGTGGTCGGATAAATATTTGGCCCGCGAAATAAGGCAGAGGTTAG
TGTTGCATAAATAGCGAGCTACGCTCGTGAGCGCTCCTAACCGAGTTGAAGCATTCCTCC
TCGCCTTTCATAAGACAGCTATGGAACTATTGCCCAGCTGTTGTTAGACGCCGCAGCCAC
ATCCCGAGTTTGGCGGCCCACGAACCGTAACTAGCCGCCCCATGGGCTAAGGTCTCGCTG
AGGCCGCAACTACGTCCTGTGGGACCAAAAGCATCTGGAAGGAAGCGTCGAAGCGGTTTT
CATAGAACTTGGGCAAGACCGACCGCAGACCTTTTTAATGCGAT'''.split())


def lgsq(a, b):
    # t stores the length of lgsq
    t = [[0]*(len(b)+1)]
    add=[]
    for i in range(1, len(a)+1):
        t.append([0]*(len(b)+1))
        for j in range(1, len(b)+1):
            if a[i-1] == b[j-1]:
                t[i][j] = t[i-1][j-1] + 1
                add.append([i, j])
            else:
                t[i][j] = max(t[i-1][j], t[i][j-1])

    # find the elements of lgsq
    sub = ''
    i, j = len(a), len(b)
    while t[i][j] > 0:
        if [i, j] in add:
            sub += a[i-1]
            i-=1
            j-=1
        elif t[i-1][j] > t[i][j-1]:
            i-=1
        else:
            j-=1
    return sub[::-1]


a = 'ACTCTTCCACCCAGACCTTCAGTCTCAGCCCTCTCATAAAGAAGAGTGGGCAATTATGATTGTCCTGAAGAACTGCCTGTCGGTCTGT'
b = 'CCATTTAGAATCCCAGAGATCCTGAGCCAGAGCCGGGCGTTACCCGTGGACAAGTCTACCTCGGCCGCGCCTAAAGCGGAATC'
print(lgsq(a, b))
