def dna_revc(dna):
    return dna.replace('A', 't').replace('T', 'a').replace('C', 'g').replace('G', 'c').upper()[::-1]

dna = '''ATATGTCTTTGTATCCACGACATACTCACACGCGCGAAACCGAATAGCAACCCTGTGAAG
GGCCCTACAGTAGAGGTGCAAAGTGTCTGGCTTCAATGTCGAGCCAACGCAGCCTTACCT
GACTGGTTACCATCTAGTCTGCCCGGGCTACAAGGGGAAGCATTCCATTTGAAAGTCACC
ATGGTGAGCTTCTTTTGCTGTGTGCTTACATCGAGACGGGTGAGAGGGCTTTCGCAGAGT
TGCCCTGACCAAGTCAGCCTGCCTTCGTCCGCAAAGGCAACGACGAAACGGATGGATTTC
ATTCTCCCTTGCCCGAATCTAACGGTACCAGGGGTGTGGCGGGAACCTTCAATAACCTGT
GCCTACAAGTGGTCTGATTTGCCAAAAAGGGTGGTACTCCTGGTCGGTCTCAGACCGGTC
TGCACGCGGTAAATGAGGGTAGGCAGTAAATTAAATATTCAATTAAAGTCGCGTGCTTCT
TCTCCTCGCACCATTTAGACCCACGACCGGTTGTCGTTTGCGTATATGTTTGCTTCCTGT
GGTCAGGGTGAAGCATCCATGCTTCGCGGATAAGGACACGATACGATGCCGAGATCGAAC
AGTCGTTGAATCAACGATCGTAAGACGGATCAAGCGGGTTCTGGAGGAAAATGTATTGAG
ACTTGTTTCCAGCTTTATGTCTTGTTACATTCGTTTCGGTAATTTGTACGCGTAGCTCAA
CGGACCCGTCCTCTATGATAGCAGAATGAGAGTCCTTACGTAGCCCTACTTATGCATAAG
TTAACGCAGGTGCAACGCGGGAGGCTCCCAGTGATAGTTTTCCCAGGCGCGC'''.split()
dna = ''.join(dna)

for n in range(0, len(dna)):
    for i in range(2, 7):
        if n + 2*i <= len(dna):
            if dna_revc(dna[n:n+i]) == dna[n+i:n+2*i]:
                print(n+1, 2*i)
        else:
            break
