s = ''.join('''GCTTGTCATGCCTGCATGGTCGCGCCCAAACTCTGAGTATTTATACGTCCTAGGGTAAGT
AGAGTACTCAACGTGTAGTAGACATGCAAACCAGCTATTGTGTGTCCGTTAATCATTAAA
GGAGTCACCCGGAATCTGTAGGGTCGGGATTTGACCGATTGGTAGTCACCCGCCTTCCAG
GCCTGTCCACGCTCATGGAGAGGTCGGGCGACAGTCTTCCGATGCGGAATAACACGAGCT
CCCATGTGGATGAATAGATGCGCCTGCATGCTTGACGCTGAGCCAGTGACGTTCCCGTTC
GCCACAAGTCGTGTAAAGAAGCTTTACTGCAGCGATGGGCATCCACGTCGCGTGTTGCTC
AAGTTTAGACGCGCTGTGAACTGATACGGCTAGTCGCCCGTCCACACCTTGGCACAGGGT
GCGACTCGATCCGAGTAAGGGTTCATCTGGCCTACAAACCTGTATCTCAAGTTCCTCTCC
CCCGACCCCATGGAAGACCAGTACTGCAAGTAAATGATGACTTTATTCACGGTCGCCTGT
CGCTCACCCTTGCGATAGCTGTGCCACTGAGTAACGGTTAGCACGCAGCTCGACAAGGAC
CAAAGCGGGGTAGTGGTGTTTAGATAACCCCCGTCTTGTCATGGAACGCAGAGCAATAAC
CCTTCCTTAGATGCCTTAGGTCCAATAGTTTGACCACGAGGCGGCCCAATAGTTGGCGAG
CCCTTCCGCCTTTACGGGAACTACCCCATGGTTTTTAATACAGCTACCATGGATGGCCTA
GACATGGGGAGCTTGCGGCACTGGTCCATAGACCTACTACTGCTACGGGCAACAAAACAT
GTAAACGGGTAATACGCAATGACCCCTCTGCCCGATGCCTAGTAGCCAAAGCATAGTCCC
TAGGA'''.split())

t = ''.join('''CCTACTAGTCGGTCGCGCGCGGAACTGC'''.split())

pos=[]
r=0
for n in t:
    for i in range(r, len(s)):
        if n == s[i]:
            pos.append(str(i+1))
            r = i+1
            break

print(' '.join(pos))
