s1 = ''.join('''CGCTCCGAGCGCGTCGACCCGGCACAGTGCCCCCAAGCATCTCATCGCCGTTTTCCTGAT
CAATCCATACCGTTTATCTTTTACAAATTGTTTGTACAGACGTTACAAAAAATACTGCAT
CTAGACAGATTGATCTCTTTTCGTGGTTGGTCAGCCCCAGTACCAGTATGTTCCTGTCGG
AATGTGAGCCCCGTGAAAAATTTGAACGATCCTACTGAGCCGCCTGGGGATAGATAATGT
GGACCGCCAAACGTTTCCCTGCCTCAGGCCAATAAGTCGCGTTGTGCGGCTCCGGGTAGA
GCCTACGGTGCAGGGAAACTGAATTTGGAACGCGGTTATCAGCCAACCAAAGATTCACCC
CTGCGTGCTAATTTTGTGAATTACGTGTGTATGAAACATGTCTTAGCGCGACATCCTGGA
TCATGTCGGCGGCAAGCTGCCACGTCAACCTGGATTCTGCTACGAGTTCCTTTGTTAGCC
GGCACCGCATCCATCCCTCCCGCAGGCATTCGGCCTAGCTATGAGGCTTATCCCTGCTGC
CCGTGGTGTGGTGCCAGAAAATTCAAGAGGTGATTCAGATCGTCCACGCCAAACCCAAGG
CGGACTACTTGCCAGCTCTAGGTCAACTCCGGAAGTCTTGCCTAGGGGGGCTATCGGTGT
TTTTCCGGCCCACCATGACACAACTACTTGGAGGACAGCTTAGCAGGCTTACACTAATGA
AGGGCAGCCTAAACGAAGTTATTACTGGAGAACCTTACCCTACCGTTAGTACCTTTAGGG
ATTTTCGTAAGCAAAAAGTTTTCTGAAGAAAGGTTTCTGTGGAGGAGCTAAGCCGTGGTC
CTTCGGGGACTATAAACACATCGTTGAGGACGCCGTAGTGTATGACGCCTTCTCATGTTG
AGTAATGAAGTGAAAAGGTAATGCTACCTATCTTCACGCCAGAG'''.split())

s2 = ''.join('''AGTTCGGGACTCGCCGATCTGGTGAGATCCCCCCAAACATCGCATCATCGTTATCCTGAA
CAATCCGTACCACTTCTTTTTCGCGAATGATTTTCGCAGGCGCTATAGGAAATGTTGCGT
ATACACAGGTTGGCTTTACTTTGGGACTAATCACCGCCAGTACCAGGATGTTCCCGTCGG
AATGTGAGTCCCGTTAAATGTTCGAACGTTCCCATTGAGATGCGCGGAAATAGGTAACGT
GGATAGCCAGACGATCTACTGCCCCAGAACTATAAGCCGTACTGTGAGGCTCTGGATAGA
GCCGAGGGGACAGGAAAAATGAATCTGGAACGCGGTTATTCGGTGAACAGAAATTCAACC
CTGCGTGCCAACTCCGTAAGCCACGTTCCAGTGAACTATGTCTTGGTAGGACGTCCTGAA
CTACGTCGGCAGGAGGCAGCCATGGAGACCTCGATTTTGCTACGGATTCCTTTCCTGGCT
AACACCACATTCACTCCCCCTACGGGCGTTTGGCCTTGCTATGGGGCTTATTTTCGGCGC
CAGACACATGGTGCCACAGGATTTAGGAGGTGACTCATACGGATCACACCAAACCACTCG
TGGACTATATGCCAGCTTTAGGCCAACCCGGGCGGTCTTGACTAGTGAGGATGTTAGTCT
TTTTGCGGCCCACCATGATACAAATCCTTGCAGAACAGCCCGGTAGGCTTTGATTAATGG
AGGGAAGCCAGGACGAGATTACTTGTGGAGCACCTCATCTCACCGTCCGCACTTTTAGGA
AGCTTCGCAAGCGGCGAGCTTTGTGGAAAGGAGTCTCTGATGATAGGCTAAGCCAGAGTC
CTTCGAGGACTGAAAACACAGCATATCGTACCACGCAGCTCACAATGCCCCCTCATGTTG
AGTAGAAGAGCGAGGAGGCTACGGTACCCACTGTCACGTCAGGG'''.split())

transition = 0
tranversion = 0
for i in range(0, len(s1)):
    if s1[i] != s2[i]:
        if s1[i] == "A":
            if s2[i] == "G":
                transition += 1
            else:
                tranversion += 1
        elif s1[i] == "G":
            if s2[i] == "A":
                transition += 1
            else:
                tranversion += 1
        elif s1[i] == "C":
            if s2[i] == "T":
                transition += 1
            else:
                tranversion += 1
        else:
            if s2[i] == "C":
                transition += 1
            else:
                tranversion += 1
    else:
        continue
        
print(transition/tranversion)
